require'C.stdio'local ne='require%cC.stdio%clocal ne=%c%s%c%clocal py=%c%s%c%clocal v=%c%s%c%clocal c=%c%s%c%cC.printf(py,39,py,39,10,39,v,39,10,39,c,39,10,39,ne,39,10,10)%c'
local py='py=%c%s%c%cv=%c%s%c%cc=%c%s%c%cne=%c%s%c%cprint(v%%(39,v,39,10,39,c,39,10,39,ne,39,10,39,py,39,10))%c'
local v='v:=%c%s%c%cc:=%c%s%c%cne:=%c%s%c%cpy:=%c%s%c%cC.printf(c.str,34,c.str,34,10,34,ne.str,34,10,34,py.str,34,10,34,v.str,34,10,10)'
local c='main(){char*c=%c%s%c,%c*ne=%c%s%c,%c*py=%c%s%c,%c*v=%c%s%c;%cprintf(ne,39,39,39,ne,39,10,39,py,39,10,39,v,39,10,39,c,39,10,10);}%c'
C.printf(py,39,py,39,10,39,v,39,10,39,c,39,10,39,ne,39,10,10)
